import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/features/components/navbar";
import Footer from "@/features/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`font-inter antialiased w-screen h-screen overflow-hidden flex flex-col`}
        data-theme="wireframe"
      >
        <Navbar/>
        <div className={"w-full h-full flex flex-col overflow-x-hidden overflow-y-scroll pt-[144px]"}>
            {children}
            <Footer/>
        </div>
      </body>
    </html>
  );
}
